/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RemNoteFlashcardsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/types.ts
var RATING_QUALITY = {
  again: 0,
  hard: 3,
  good: 4,
  easy: 5
};
var DEFAULT_SETTINGS = {
  examGroups: [],
  dailyReminderEnabled: true,
  aiEnabled: false,
  aiBaseUrl: "http://localhost:11434/v1",
  aiApiKey: "ollama",
  aiModel: "starter-agent",
  newCardsPerDay: 20,
  cardSyntaxBasic: "::",
  cardSyntaxDropdown: ":::",
  pdfAttachmentFolder: "Attachments/PDFs"
};
function cardBelongsToGroup(card, group) {
  for (const p of group.paths) {
    if (p.endsWith("/")) {
      if (card.filePath.startsWith(p))
        return true;
    } else {
      if (card.filePath === p)
        return true;
    }
  }
  return false;
}

// src/parser.ts
var import_crypto = require("crypto");
function cardId(filePath, front, line) {
  return (0, import_crypto.createHash)("md5").update(`${filePath}::${line}::${front}`).digest("hex").slice(0, 12);
}
function isContinuationLine(line) {
  if (line.trim() === "")
    return false;
  return /^[\t ]/.test(line) || /^\s*[-*+]\s/.test(line) || /^\s*\d+\.\s/.test(line);
}
function parseFlashcards(content, filePath) {
  var _a, _b, _c;
  const cards = [];
  const lines = content.split("\n");
  let startLine = 0;
  if (((_a = lines[0]) == null ? void 0 : _a.trim()) === "---") {
    for (let i2 = 1; i2 < lines.length; i2++) {
      if (((_b = lines[i2]) == null ? void 0 : _b.trim()) === "---") {
        startLine = i2 + 1;
        break;
      }
    }
  }
  let i = startLine;
  while (i < lines.length) {
    const line = lines[i];
    if (line.trim().startsWith("```")) {
      i++;
      while (i < lines.length && !((_c = lines[i]) == null ? void 0 : _c.trim().startsWith("```")))
        i++;
      i++;
      continue;
    }
    const dropIdx = findSeparator(line, ":::");
    if (dropIdx !== -1) {
      const front = cleanFront(line.slice(0, dropIdx));
      const firstBack = line.slice(dropIdx + 3).trim();
      if (front) {
        const { back, consumed } = collectBack(firstBack, lines, i + 1);
        cards.push({ id: cardId(filePath, front, i), filePath, front, back, type: "dropdown", line: i });
        i += consumed;
      }
      i++;
      continue;
    }
    const basicIdx = findSeparator(line, "::");
    if (basicIdx !== -1) {
      const front = cleanFront(line.slice(0, basicIdx));
      const firstBack = line.slice(basicIdx + 2).trim();
      if (front) {
        const { back, consumed } = collectBack(firstBack, lines, i + 1);
        cards.push({ id: cardId(filePath, front, i), filePath, front, back, type: "basic", line: i });
        i += consumed;
      }
      i++;
      continue;
    }
    i++;
  }
  return cards;
}
function collectBack(inlinePart, lines, nextLine) {
  const parts = [];
  if (inlinePart)
    parts.push(inlinePart);
  let j = nextLine;
  while (j < lines.length && isContinuationLine(lines[j])) {
    parts.push(lines[j].trimStart());
    j++;
  }
  return {
    back: parts.join("\n"),
    consumed: j - nextLine
  };
}
function cleanFront(raw) {
  return raw.replace(/^[\s]*[-*+]\s+/, "").replace(/^\s*\d+\.\s+/, "").replace(/^\s*#+\s+/, "").trim();
}
function findSeparator(line, sep) {
  let inCode = false;
  let inLink = 0;
  for (let i = 0; i <= line.length - sep.length; i++) {
    const ch = line[i];
    if (ch === "`")
      inCode = !inCode;
    if (!inCode && ch === "[")
      inLink++;
    if (!inCode && ch === "]")
      inLink = Math.max(0, inLink - 1);
    if (!inCode && inLink === 0 && line.slice(i, i + sep.length) === sep) {
      if (sep === "::" && line[i + 2] === ":")
        continue;
      return i;
    }
  }
  return -1;
}

// src/sm2.ts
var MIN_EF = 1.3;
function todayStr() {
  return new Date().toISOString().slice(0, 10);
}
function addDays(dateStr, days) {
  const d = new Date(dateStr);
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}
function daysBetween(a, b) {
  const msPerDay = 864e5;
  return Math.round((new Date(b).getTime() - new Date(a).getTime()) / msPerDay);
}
function newRecord(cardId2) {
  return {
    cardId: cardId2,
    interval: 0,
    easeFactor: 2.5,
    repetitions: 0,
    dueDate: todayStr(),
    lastReviewed: null
  };
}
function applyRating(record, rating) {
  const q = RATING_QUALITY[rating];
  const today = todayStr();
  let { interval, easeFactor, repetitions } = record;
  if (q < 3) {
    repetitions = 0;
    interval = 1;
  } else {
    if (repetitions === 0) {
      interval = 1;
    } else if (repetitions === 1) {
      interval = 6;
    } else {
      interval = Math.round(interval * easeFactor);
    }
    repetitions += 1;
  }
  easeFactor = easeFactor + (0.1 - (5 - q) * (0.08 + (5 - q) * 0.02));
  if (easeFactor < MIN_EF)
    easeFactor = MIN_EF;
  return {
    ...record,
    interval,
    easeFactor,
    repetitions,
    dueDate: addDays(today, interval),
    lastReviewed: today
  };
}
function isDue(record) {
  return record.dueDate <= todayStr();
}

// src/scheduler.ts
function buildDailySession(cards, data, examDate, groupName) {
  const { reviews } = data;
  const today = todayStr();
  const dueCards = [];
  const newCards = [];
  for (const card of cards) {
    const rec = reviews[card.id];
    if (!rec) {
      newCards.push(card);
    } else if (isDue(rec)) {
      dueCards.push(card);
    }
  }
  let newCardQuota = data.settings.newCardsPerDay;
  let daysUntilExam = null;
  if (examDate) {
    const days = daysBetween(today, examDate);
    daysUntilExam = days;
    if (days > 0 && newCards.length > 0) {
      const effectiveDays = Math.max(1, Math.floor(days * 0.8));
      newCardQuota = Math.ceil(newCards.length / effectiveDays);
      newCardQuota = Math.min(newCardQuota, 50);
    } else if (days <= 0) {
      newCardQuota = newCards.length;
    }
  }
  return {
    dueCards,
    newCards: newCards.slice(0, newCardQuota),
    totalDue: dueCards.length,
    newCardQuota,
    daysUntilExam,
    groupName: groupName != null ? groupName : null
  };
}
function getSessionCards(session) {
  return [...session.dueCards, ...session.newCards];
}
function cardsForGroup(allCards, group) {
  return allCards.filter((c) => cardBelongsToGroup(c, group));
}
function cardsWithoutGroup(allCards, data) {
  const { examGroups } = data.settings;
  if (examGroups.length === 0)
    return allCards;
  return allCards.filter(
    (c) => !examGroups.some((g) => cardBelongsToGroup(c, g))
  );
}
function cardsForPath(allCards, filePath) {
  return allCards.filter((c) => c.filePath === filePath);
}
function getStats(cards, data) {
  const reviews = data.reviews;
  let learned = 0;
  let due = 0;
  let unseen = 0;
  for (const card of cards) {
    const rec = reviews[card.id];
    if (!rec) {
      unseen++;
    } else if (isDue(rec)) {
      due++;
    } else {
      learned++;
    }
  }
  return { learned, due, unseen, total: cards.length };
}
function getTotalDueCount(allCards, data) {
  const { due } = getStats(allCards, data);
  return due;
}

// src/modal.ts
var import_obsidian = require("obsidian");

// src/ai.ts
function stripThinking(text) {
  return text.replace(/<think>[\s\S]*?<\/think>/gi, "").trim();
}
function isQwenOllama(settings) {
  const model = settings.aiModel.toLowerCase();
  const url = settings.aiBaseUrl.toLowerCase();
  const isLocal = url.includes("localhost") || url.includes("127.0.0.1");
  const isQwen = model.includes("qwen") || model.includes("deepseek");
  return isLocal && isQwen;
}
async function callAI(prompt, settings, maxTokens = 300) {
  var _a, _b, _c, _d, _e, _f, _g;
  const finalPrompt = isQwenOllama(settings) ? `/no_think ${prompt}` : prompt;
  const response = await fetch(`${settings.aiBaseUrl}/chat/completions`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${settings.aiApiKey}`
    },
    body: JSON.stringify({
      model: settings.aiModel,
      messages: [{ role: "user", content: finalPrompt }],
      temperature: 0.3,
      max_tokens: maxTokens,
      stream: false
    })
  });
  if (!response.ok) {
    const errText = await response.text().catch(() => "");
    throw new Error(`AI ${response.status}: ${errText.slice(0, 200)}`);
  }
  const json = await response.json();
  let content = (_g = (_f = (_c = (_b = (_a = json.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content) != null ? _f : (_e = (_d = json.choices) == null ? void 0 : _d[0]) == null ? void 0 : _e.text) != null ? _g : (
    // some Ollama versions
    ""
  );
  content = stripThinking(content);
  if (!content) {
    throw new Error(
      "Keine Antwort vom Modell.\nPr\xFCfe Modellname, API Key und Base URL.\n(Rohinhalt: " + JSON.stringify(json).slice(0, 150) + ")"
    );
  }
  return content;
}
async function aiGenerateAnswer(question, context, settings) {
  if (!settings.aiEnabled)
    return "";
  const prompt = context ? `You are a study assistant. Based on these notes:

${context}

Answer this question concisely (max 2 sentences):
${question}` : `You are a study assistant. Answer this question concisely in 1-2 sentences. Give only the answer, no preamble:
${question}`;
  return callAI(prompt, settings, 150);
}
async function aiExplainAnswer(question, answer, settings) {
  if (!settings.aiEnabled)
    return "";
  const prompt = `You are a study assistant. Briefly explain (2-3 sentences) why this answer is correct:

Question: ${question}
Answer: ${answer}

Reply in the same language as the question. Use an example if it helps.`;
  return callAI(prompt, settings, 250);
}

// src/modal.ts
var ReviewModal = class extends import_obsidian.Modal {
  constructor(app, plugin, cards, data) {
    super(app);
    this.currentIndex = 0;
    this.keyHandler = null;
    this.plugin = plugin;
    this.cards = cards;
    this.data = data;
  }
  onOpen() {
    this.modalEl.addClass("remnote-review-modal");
    this.renderCard();
  }
  onClose() {
    if (this.keyHandler) {
      document.removeEventListener("keydown", this.keyHandler);
      this.keyHandler = null;
    }
    this.contentEl.empty();
  }
  get currentCard() {
    return this.cards[this.currentIndex];
  }
  async renderCard() {
    const { contentEl } = this;
    contentEl.empty();
    if (this.keyHandler) {
      document.removeEventListener("keydown", this.keyHandler);
      this.keyHandler = null;
    }
    if (this.currentIndex >= this.cards.length) {
      this.renderFinished();
      return;
    }
    const card = this.currentCard;
    const progressWrap = contentEl.createDiv("remnote-progress-wrap");
    const progressBar = progressWrap.createDiv("remnote-progress-bar");
    progressBar.style.width = `${this.currentIndex / this.cards.length * 100}%`;
    progressWrap.createEl("span", {
      text: `${this.currentIndex + 1} / ${this.cards.length}`,
      cls: "remnote-progress-text"
    });
    const topRow = contentEl.createDiv("remnote-top-row");
    const badge = topRow.createDiv("remnote-card-badge");
    badge.setText(card.type === "basic" ? "Karteikarte" : "Dropdown");
    const sourceBtn = topRow.createEl("button", {
      cls: "remnote-btn-source",
      title: "In Notiz \xF6ffnen"
    });
    sourceBtn.innerHTML = `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/><polyline points="15 3 21 3 21 9"/><line x1="10" y1="14" x2="21" y2="3"/></svg> Quelle`;
    sourceBtn.onclick = () => this.openSource(card);
    const frontEl = contentEl.createDiv("remnote-card-front");
    await import_obsidian.MarkdownRenderer.render(this.app, card.front, frontEl, card.filePath, this.plugin);
    if (card.type === "dropdown") {
      const dropEl = contentEl.createDiv("remnote-dropdown-answer");
      dropEl.addClass("remnote-blurred");
      await import_obsidian.MarkdownRenderer.render(this.app, card.back, dropEl, card.filePath, this.plugin);
      const revealBtn = contentEl.createEl("button", {
        text: "Antwort anzeigen",
        cls: "remnote-btn remnote-btn-reveal"
      });
      revealBtn.onclick = () => {
        dropEl.removeClass("remnote-blurred");
        revealBtn.style.display = "none";
        this.showAnswerActions(contentEl, card);
      };
      this.keyHandler = (e) => {
        if (e.key === " " && !this.isRatingVisible(contentEl)) {
          e.preventDefault();
          revealBtn.click();
        }
      };
      document.addEventListener("keydown", this.keyHandler);
    } else {
      const flipBtn = contentEl.createEl("button", {
        text: "Umdrehen  [Space]",
        cls: "remnote-btn remnote-btn-reveal"
      });
      flipBtn.onclick = async () => {
        flipBtn.style.display = "none";
        const answerEl = contentEl.createDiv("remnote-card-back");
        await import_obsidian.MarkdownRenderer.render(this.app, card.back, answerEl, card.filePath, this.plugin);
        this.showAnswerActions(contentEl, card);
      };
      this.keyHandler = (e) => {
        if (e.key === " " && !this.isRatingVisible(contentEl)) {
          e.preventDefault();
          flipBtn.click();
        }
      };
      document.addEventListener("keydown", this.keyHandler);
    }
  }
  isRatingVisible(container) {
    return !!container.querySelector(".remnote-rating-wrap");
  }
  showAnswerActions(container, card) {
    if (this.plugin.pluginData.settings.aiEnabled) {
      const aiRow = container.createDiv("remnote-ai-row");
      const aiBtn = aiRow.createEl("button", {
        text: "\u2726 Erkl\xE4ren",
        cls: "remnote-btn remnote-btn-ai"
      });
      aiBtn.onclick = async () => {
        aiBtn.disabled = true;
        aiBtn.setText("Erkl\xE4re...");
        try {
          const explanation = await aiExplainAnswer(
            card.front,
            card.back,
            this.plugin.pluginData.settings
          );
          aiBtn.style.display = "none";
          const aiEl = container.createDiv("remnote-ai-answer");
          aiEl.createEl("span", { text: "\u2726 ", cls: "remnote-ai-label" });
          await import_obsidian.MarkdownRenderer.render(this.app, explanation, aiEl, card.filePath, this.plugin);
        } catch (e) {
          aiBtn.disabled = false;
          aiBtn.setText("\u2726 Erkl\xE4ren");
          new import_obsidian.Notice("AI Fehler: " + e.message);
        }
      };
    }
    this.showRatingButtons(container, card);
  }
  showRatingButtons(container, card) {
    const ratingWrap = container.createDiv("remnote-rating-wrap");
    ratingWrap.createEl("p", {
      text: "Wie gut wusstest du die Antwort?",
      cls: "remnote-rating-label"
    });
    const buttons = [
      { rating: "again", label: "Wieder", key: "1" },
      { rating: "hard", label: "Schwer", key: "2" },
      { rating: "good", label: "Gut", key: "3" },
      { rating: "easy", label: "Einfach", key: "4" }
    ];
    const btnRow = ratingWrap.createDiv("remnote-rating-buttons");
    for (const { rating, label, key } of buttons) {
      const btn = btnRow.createEl("button", {
        cls: `remnote-btn remnote-btn-rating remnote-rating-${rating}`
      });
      btn.innerHTML = `<span class="remnote-rating-key">${key}</span>${label}`;
      btn.onclick = () => this.submitRating(rating);
    }
    if (this.keyHandler) {
      document.removeEventListener("keydown", this.keyHandler);
    }
    this.keyHandler = (e) => {
      if (e.key === "1")
        this.submitRating("again");
      else if (e.key === "2")
        this.submitRating("hard");
      else if (e.key === "3")
        this.submitRating("good");
      else if (e.key === "4")
        this.submitRating("easy");
      else
        return;
      document.removeEventListener("keydown", this.keyHandler);
      this.keyHandler = null;
    };
    document.addEventListener("keydown", this.keyHandler);
  }
  async submitRating(rating) {
    var _a;
    const card = this.currentCard;
    const existing = (_a = this.data.reviews[card.id]) != null ? _a : newRecord(card.id);
    this.data.reviews[card.id] = applyRating(existing, rating);
    await this.plugin.savePluginData();
    this.currentIndex++;
    await this.renderCard();
  }
  async openSource(card) {
    const file = this.app.vault.getAbstractFileByPath(card.filePath);
    if (!(file instanceof import_obsidian.TFile)) {
      new import_obsidian.Notice("Datei nicht gefunden: " + card.filePath);
      return;
    }
    this.close();
    const leaf = this.app.workspace.getLeaf(false);
    await leaf.openFile(file);
    const view = leaf.view;
    if (view == null ? void 0 : view.editor) {
      view.editor.setCursor({ line: card.line, ch: 0 });
      view.editor.scrollIntoView(
        { from: { line: card.line, ch: 0 }, to: { line: card.line, ch: 999 } },
        true
      );
    }
  }
  renderFinished() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createDiv("remnote-finished-icon").setText("\u2713");
    contentEl.createEl("h2", { text: "Sitzung abgeschlossen!", cls: "remnote-finished-title" });
    contentEl.createEl("p", {
      text: `${this.cards.length} Karten bearbeitet.`,
      cls: "remnote-finished-sub"
    });
    const doneBtn = contentEl.createEl("button", {
      text: "Schlie\xDFen",
      cls: "remnote-btn remnote-btn-reveal"
    });
    doneBtn.onclick = () => this.close();
  }
};

// src/session-picker.ts
var import_obsidian2 = require("obsidian");
var SessionPickerModal = class extends import_obsidian2.Modal {
  constructor(app, plugin, allCards) {
    super(app);
    this.plugin = plugin;
    this.allCards = allCards;
  }
  onOpen() {
    this.modalEl.addClass("remnote-picker-modal");
    this.render();
  }
  onClose() {
    this.contentEl.empty();
  }
  render() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Lernsitzung starten", cls: "remnote-picker-title" });
    const data = this.plugin.pluginData;
    const groups = data.settings.examGroups;
    if (groups.length > 0) {
      contentEl.createEl("h3", { text: "Pr\xFCfungen", cls: "remnote-picker-section" });
      for (const group of groups) {
        const groupCards = cardsForGroup(this.allCards, group);
        const session = buildDailySession(groupCards, data, group.examDate, group.name);
        const stats = getStats(groupCards, data);
        const today = session.dueCards.length + session.newCards.length;
        const daysLeft = group.examDate ? daysBetween(todayStr(), group.examDate) : null;
        const row = contentEl.createDiv("remnote-picker-row");
        const info = row.createDiv("remnote-picker-info");
        info.createEl("div", { text: group.name, cls: "remnote-picker-name" });
        const meta = info.createDiv("remnote-picker-meta");
        if (daysLeft !== null) {
          const dayEl = meta.createEl("span", {
            text: daysLeft > 0 ? `\u{1F4C5} ${daysLeft} Tage` : daysLeft === 0 ? "\u{1F4C5} Heute!" : "\u26A0\uFE0F Vorbei",
            cls: daysLeft <= 3 ? "remnote-picker-urgent" : "remnote-picker-day"
          });
        }
        meta.createEl("span", { text: ` \xB7 ${today} heute`, cls: "remnote-picker-due" });
        meta.createEl("span", { text: ` \xB7 ${stats.unseen} neu`, cls: "remnote-picker-new" });
        meta.createEl("span", { text: ` \xB7 ${stats.total} gesamt`, cls: "remnote-picker-total" });
        const startBtn = row.createEl("button", {
          text: today > 0 ? `Lernen (${today})` : "Alle gelernt \u2713",
          cls: today > 0 ? "remnote-btn remnote-picker-btn" : "remnote-btn remnote-picker-btn-done"
        });
        startBtn.disabled = today === 0;
        startBtn.onclick = () => {
          this.close();
          const cards = getSessionCards(session);
          new ReviewModal(this.app, this.plugin, cards, data).open();
        };
      }
    }
    contentEl.createEl("h3", { text: "Weitere Optionen", cls: "remnote-picker-section" });
    {
      const ungroupedCards = groups.length > 0 ? cardsWithoutGroup(this.allCards, data) : this.allCards;
      const sessionAll = buildDailySession(this.allCards, data);
      const todayAll = sessionAll.dueCards.length + sessionAll.newCards.length;
      const row = contentEl.createDiv("remnote-picker-row");
      const info = row.createDiv("remnote-picker-info");
      info.createEl("div", { text: "Alle Karten", cls: "remnote-picker-name" });
      info.createDiv("remnote-picker-meta").createEl("span", {
        text: `${todayAll} heute f\xE4llig \xB7 ${this.allCards.length} gesamt`,
        cls: "remnote-picker-total"
      });
      const btn = row.createEl("button", {
        text: todayAll > 0 ? `Lernen (${todayAll})` : "Alle gelernt \u2713",
        cls: todayAll > 0 ? "remnote-btn remnote-picker-btn" : "remnote-btn remnote-picker-btn-done"
      });
      btn.disabled = todayAll === 0;
      btn.onclick = () => {
        this.close();
        new ReviewModal(this.app, this.plugin, getSessionCards(sessionAll), data).open();
      };
    }
    {
      const activeFile = this.app.workspace.getActiveFile();
      if (activeFile) {
        const noteCards = cardsForPath(this.allCards, activeFile.path);
        const stats = getStats(noteCards, data);
        const row = contentEl.createDiv("remnote-picker-row");
        const info = row.createDiv("remnote-picker-info");
        info.createEl("div", { text: `Aktive Notiz`, cls: "remnote-picker-name" });
        info.createDiv("remnote-picker-meta").createEl("span", {
          text: `${activeFile.basename} \xB7 ${stats.due} f\xE4llig \xB7 ${stats.total} gesamt`,
          cls: "remnote-picker-total"
        });
        const btn = row.createEl("button", {
          text: noteCards.length > 0 ? `Lernen (${noteCards.length})` : "Keine Karten",
          cls: "remnote-btn remnote-picker-btn"
        });
        btn.disabled = noteCards.length === 0;
        btn.onclick = () => {
          this.close();
          new ReviewModal(this.app, this.plugin, noteCards, data).open();
        };
      }
    }
    contentEl.createEl("h3", { text: "Notiz ausw\xE4hlen", cls: "remnote-picker-section" });
    this.renderFileBrowser(contentEl);
  }
  renderFileBrowser(container) {
    var _a, _b;
    const data = this.plugin.pluginData;
    const byFile = /* @__PURE__ */ new Map();
    for (const card of this.allCards) {
      if (!byFile.has(card.filePath))
        byFile.set(card.filePath, []);
      byFile.get(card.filePath).push(card);
    }
    if (byFile.size === 0) {
      container.createEl("p", { text: "Keine Karteikarten im Vault gefunden.", cls: "remnote-picker-empty" });
      return;
    }
    const fileList = container.createDiv("remnote-file-list");
    const sorted = [...byFile.entries()].sort(([, a], [, b]) => {
      const dueA = getStats(a, data).due;
      const dueB = getStats(b, data).due;
      return dueB - dueA;
    });
    for (const [filePath, cards] of sorted) {
      const stats = getStats(cards, data);
      const fileName = (_b = (_a = filePath.split("/").pop()) == null ? void 0 : _a.replace(".md", "")) != null ? _b : filePath;
      const row = fileList.createDiv("remnote-picker-row remnote-file-row");
      const info = row.createDiv("remnote-picker-info");
      info.createEl("div", { text: fileName, cls: "remnote-picker-name remnote-picker-name-sm" });
      const meta = info.createDiv("remnote-picker-meta");
      if (stats.due > 0)
        meta.createEl("span", { text: `${stats.due} f\xE4llig`, cls: "remnote-picker-due" });
      if (stats.unseen > 0)
        meta.createEl("span", { text: ` \xB7 ${stats.unseen} neu`, cls: "remnote-picker-new" });
      meta.createEl("span", { text: ` \xB7 ${stats.total} gesamt`, cls: "remnote-picker-total" });
      const btn = row.createEl("button", {
        text: "Lernen",
        cls: "remnote-btn remnote-picker-btn-sm"
      });
      btn.onclick = () => {
        this.close();
        new ReviewModal(this.app, this.plugin, cards, data).open();
      };
    }
  }
};

// src/browse-modal.ts
var import_obsidian3 = require("obsidian");
function classifyCard(card, data) {
  const rec = data.reviews[card.id];
  if (!rec)
    return "new";
  if (rec.repetitions === 0)
    return "again";
  if (rec.interval <= 6)
    return "hard";
  if (rec.interval <= 20)
    return "good";
  return "easy";
}
var TAB_LABELS = {
  all: "Alle",
  new: "Neu",
  again: "Wieder",
  hard: "Schwer",
  good: "Gut",
  easy: "Einfach"
};
var TAB_COLORS = {
  all: "",
  new: "#888",
  again: "#e05252",
  hard: "#d4870a",
  good: "#2d8a4e",
  easy: "#1a7abf"
};
var BrowseModal = class extends import_obsidian3.Modal {
  constructor(app, plugin, allCards, data) {
    super(app);
    this.activeTab = "all";
    this.expandedIds = /* @__PURE__ */ new Set();
    this.searchQuery = "";
    this.plugin = plugin;
    this.allCards = allCards;
    this.data = data;
  }
  onOpen() {
    this.modalEl.addClass("remnote-browse-modal");
    this.render();
  }
  onClose() {
    this.contentEl.empty();
  }
  buildList() {
    return this.allCards.map((card) => {
      var _a;
      return {
        card,
        tab: classifyCard(card, this.data),
        record: (_a = this.data.reviews[card.id]) != null ? _a : null
      };
    });
  }
  render() {
    const { contentEl } = this;
    contentEl.empty();
    const all = this.buildList();
    const counts = { all: all.length, new: 0, again: 0, hard: 0, good: 0, easy: 0 };
    for (const c of all)
      counts[c.tab]++;
    contentEl.createEl("h2", { text: "Karteikarten", cls: "remnote-browse-title" });
    const searchRow = contentEl.createDiv("remnote-browse-search-row");
    const searchInput = searchRow.createEl("input", {
      type: "text",
      placeholder: "Suchen...",
      cls: "remnote-browse-search"
    });
    searchInput.value = this.searchQuery;
    searchInput.oninput = () => {
      this.searchQuery = searchInput.value;
      this.renderList(listContainer, all, counts);
    };
    const tabBar = contentEl.createDiv("remnote-browse-tabs");
    const tabs = ["all", "new", "again", "hard", "good", "easy"];
    for (const tab of tabs) {
      const btn = tabBar.createEl("button", {
        cls: "remnote-browse-tab" + (tab === this.activeTab ? " active" : "")
      });
      btn.innerHTML = `<span class="remnote-browse-tab-label">${TAB_LABELS[tab]}</span><span class="remnote-browse-tab-count" style="background:${TAB_COLORS[tab] || "var(--tag-background)"}">${counts[tab]}</span>`;
      btn.onclick = () => {
        this.activeTab = tab;
        tabBar.querySelectorAll(".remnote-browse-tab").forEach((el) => el.removeClass("active"));
        btn.addClass("active");
        this.renderList(listContainer, all, counts);
      };
    }
    const listContainer = contentEl.createDiv("remnote-browse-list");
    this.renderList(listContainer, all, counts);
  }
  renderList(container, all, counts) {
    var _a, _b;
    container.empty();
    const q = this.searchQuery.toLowerCase();
    const filtered = all.filter((c) => {
      if (this.activeTab !== "all" && c.tab !== this.activeTab)
        return false;
      if (q && !c.card.front.toLowerCase().includes(q) && !c.card.back.toLowerCase().includes(q))
        return false;
      return true;
    });
    if (filtered.length === 0) {
      container.createEl("p", { text: "Keine Karten gefunden.", cls: "remnote-browse-empty" });
      return;
    }
    for (const { card, tab, record } of filtered) {
      const isExpanded = this.expandedIds.has(card.id);
      const row = container.createDiv("remnote-browse-card" + (isExpanded ? " expanded" : ""));
      const header = row.createDiv("remnote-browse-card-header");
      const dot = header.createSpan("remnote-browse-dot");
      dot.style.background = TAB_COLORS[tab] || "var(--tag-background)";
      dot.title = TAB_LABELS[tab];
      const frontEl = header.createDiv("remnote-browse-front");
      import_obsidian3.MarkdownRenderer.render(this.app, card.front, frontEl, card.filePath, this.plugin);
      const meta = header.createDiv("remnote-browse-meta");
      meta.createEl("span", {
        text: (_b = (_a = card.filePath.split("/").pop()) == null ? void 0 : _a.replace(".md", "")) != null ? _b : "",
        cls: "remnote-browse-file"
      });
      if (record) {
        meta.createEl("span", {
          text: `\u21BB ${record.interval}d`,
          cls: "remnote-browse-interval",
          title: `N\xE4chste Wiederholung: ${record.dueDate}`
        });
      }
      const srcBtn = meta.createEl("button", { cls: "remnote-btn-source remnote-browse-src-btn", title: "In Notiz \xF6ffnen" });
      srcBtn.innerHTML = `<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/><polyline points="15 3 21 3 21 9"/><line x1="10" y1="14" x2="21" y2="3"/></svg>`;
      srcBtn.onclick = (e) => {
        e.stopPropagation();
        this.openSource(card);
      };
      header.onclick = (e) => {
        if (e.target.closest("button"))
          return;
        if (isExpanded) {
          this.expandedIds.delete(card.id);
        } else {
          this.expandedIds.add(card.id);
        }
        this.renderList(container, all, counts);
      };
      if (isExpanded) {
        const backEl = row.createDiv("remnote-browse-back");
        import_obsidian3.MarkdownRenderer.render(this.app, card.back, backEl, card.filePath, this.plugin);
        if (record) {
          const statsEl = row.createDiv("remnote-browse-stats");
          statsEl.innerHTML = `<span>Wiederholungen: <b>${record.repetitions}</b></span><span>Intervall: <b>${record.interval} Tage</b></span><span>Ease: <b>${record.easeFactor.toFixed(2)}</b></span><span>F\xE4llig: <b>${record.dueDate}</b></span>`;
        }
      }
    }
  }
  async openSource(card) {
    const file = this.app.vault.getAbstractFileByPath(card.filePath);
    if (!(file instanceof import_obsidian3.TFile)) {
      new import_obsidian3.Notice("Datei nicht gefunden: " + card.filePath);
      return;
    }
    this.close();
    const leaf = this.app.workspace.getLeaf(false);
    await leaf.openFile(file);
    const view = leaf.view;
    if (view == null ? void 0 : view.editor) {
      view.editor.setCursor({ line: card.line, ch: 0 });
      view.editor.scrollIntoView(
        { from: { line: card.line, ch: 0 }, to: { line: card.line, ch: 999 } },
        true
      );
    }
  }
};

// src/settings.ts
var import_obsidian4 = require("obsidian");
var ExamGroupModal = class extends import_obsidian4.Modal {
  constructor(app, group, onSave) {
    super(app);
    this.group = { ...group, paths: [...group.paths] };
    this.onSave = onSave;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("remnote-group-modal");
    contentEl.createEl("h3", { text: "Pr\xFCfungsgruppe bearbeiten" });
    new import_obsidian4.Setting(contentEl).setName("Name").setDesc("z.B. 'Obstbau Klausur'").addText(
      (t) => t.setValue(this.group.name).onChange((v) => this.group.name = v)
    );
    new import_obsidian4.Setting(contentEl).setName("Pr\xFCfungsdatum").setDesc("Format: YYYY-MM-DD").addText(
      (t) => t.setPlaceholder("2026-07-15").setValue(this.group.examDate).onChange((v) => this.group.examDate = v)
    );
    new import_obsidian4.Setting(contentEl).setName("Verkn\xFCpfte Pfade").setDesc(
      "Eine Notiz oder ein Ordner pro Zeile.\nOrdner: 'Sources/VL Notizen/Agrarwissenschaften/'\nNotiz: 'Sources/VL Notizen/Agrarwissenschaften/Obstbau SS2026.md'"
    ).addTextArea((ta) => {
      ta.setValue(this.group.paths.join("\n"));
      ta.inputEl.rows = 5;
      ta.inputEl.style.width = "100%";
      ta.onChange((v) => {
        this.group.paths = v.split("\n").map((s) => s.trim()).filter(Boolean);
      });
    });
    new import_obsidian4.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Speichern").setCta().onClick(() => {
        if (!this.group.name) {
          new import_obsidian4.Notice("Bitte einen Namen eingeben.");
          return;
        }
        this.onSave(this.group);
        this.close();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};
var RemNoteSettingsTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "RemNote Flashcards \u2014 Einstellungen" });
    containerEl.createEl("h3", { text: "Pr\xFCfungen" });
    const groups = this.plugin.pluginData.settings.examGroups;
    const groupsContainer = containerEl.createDiv("remnote-settings-groups");
    this.renderGroupList(groupsContainer);
    new import_obsidian4.Setting(containerEl).setName("Neue Pr\xFCfung hinzuf\xFCgen").setDesc("Erstelle eine Pr\xFCfungsgruppe und verkn\xFCpfe sie mit Notizen oder Ordnern.").addButton(
      (btn) => btn.setButtonText("+ Hinzuf\xFCgen").onClick(() => {
        const newGroup = {
          id: Date.now().toString(),
          name: "",
          examDate: "",
          paths: []
        };
        new ExamGroupModal(this.app, newGroup, async (saved) => {
          this.plugin.pluginData.settings.examGroups.push(saved);
          await this.plugin.savePluginData();
          this.display();
        }).open();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Neue Karten pro Tag (Fallback)").setDesc("Wird verwendet, wenn kein Pr\xFCfungsdatum f\xFCr eine Karte gesetzt ist.").addSlider(
      (slider) => slider.setLimits(5, 100, 5).setValue(this.plugin.pluginData.settings.newCardsPerDay).setDynamicTooltip().onChange(async (value) => {
        this.plugin.pluginData.settings.newCardsPerDay = value;
        await this.plugin.savePluginData();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("T\xE4gliche Erinnerung").setDesc("Zeigt beim Start eine Benachrichtigung, wenn Karten f\xE4llig sind.").addToggle(
      (toggle) => toggle.setValue(this.plugin.pluginData.settings.dailyReminderEnabled).onChange(async (value) => {
        this.plugin.pluginData.settings.dailyReminderEnabled = value;
        await this.plugin.savePluginData();
      })
    );
    containerEl.createEl("h3", { text: "PDF Panel" });
    new import_obsidian4.Setting(containerEl).setName("Zielordner f\xFCr importierte PDFs").setDesc(
      "PDFs die per Drag & Drop importiert werden, landen hier im Vault.\nDieser Ordner wird von OneDrive automatisch auf alle Ger\xE4te synchronisiert."
    ).addText(
      (text) => text.setPlaceholder("Attachments/PDFs").setValue(this.plugin.pluginData.settings.pdfAttachmentFolder).onChange(async (value) => {
        this.plugin.pluginData.settings.pdfAttachmentFolder = value || "Attachments/PDFs";
        await this.plugin.savePluginData();
      })
    );
    containerEl.createEl("h3", { text: "Karten-Syntax" });
    new import_obsidian4.Setting(containerEl).setName("Basic-Karte Trennzeichen").setDesc("Standard: ::  \u2192  Frage :: Antwort").addText(
      (text) => text.setValue(this.plugin.pluginData.settings.cardSyntaxBasic).onChange(async (value) => {
        this.plugin.pluginData.settings.cardSyntaxBasic = value || "::";
        await this.plugin.savePluginData();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Dropdown-Karte Trennzeichen").setDesc("Standard: :::  \u2192  Begriff ::: Definition").addText(
      (text) => text.setValue(this.plugin.pluginData.settings.cardSyntaxDropdown).onChange(async (value) => {
        this.plugin.pluginData.settings.cardSyntaxDropdown = value || ":::";
        await this.plugin.savePluginData();
      })
    );
    containerEl.createEl("h3", { text: "AI" });
    new import_obsidian4.Setting(containerEl).setName("AI aktivieren").setDesc(
      "Aktiviert zwei Funktionen:\n1. Command 'AI Antwort generieren' beim Schreiben (Strg+P)\n2. '\u2726 Erkl\xE4ren'-Button nach dem Umdrehen einer Karte"
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.pluginData.settings.aiEnabled).onChange(async (value) => {
        this.plugin.pluginData.settings.aiEnabled = value;
        await this.plugin.savePluginData();
      })
    );
    const presets = {
      "\u{1F5A5}\uFE0F Ollama (lokal)": {
        url: "http://localhost:11434/v1",
        model: "starter-agent",
        keyHint: "ollama"
      },
      "\u26A1 NVIDIA NIM": {
        url: "https://integrate.api.nvidia.com/v1",
        model: "meta/llama-3.1-8b-instruct",
        keyHint: "nvapi-\u2026 (kostenlos auf build.nvidia.com)"
      },
      "\u2601\uFE0F OpenAI": {
        url: "https://api.openai.com/v1",
        model: "gpt-4o-mini",
        keyHint: "sk-\u2026 (platform.openai.com)"
      },
      "\u{1F500} OpenRouter": {
        url: "https://openrouter.ai/api/v1",
        model: "meta-llama/llama-3.1-8b-instruct:free",
        keyHint: "sk-or-\u2026 (openrouter.ai \u2014 hat kostenlose Modelle)"
      }
    };
    let urlInputRef = null;
    let modelInputRef = null;
    let keyHintEl = null;
    const presetSetting = new import_obsidian4.Setting(containerEl).setName("Provider Preset").setDesc("Schnellauswahl \u2014 f\xFCllt URL und Modell aus. API Key separat eintragen.");
    for (const [label, preset] of Object.entries(presets)) {
      presetSetting.addButton(
        (btn) => btn.setButtonText(label).onClick(async () => {
          this.plugin.pluginData.settings.aiBaseUrl = preset.url;
          this.plugin.pluginData.settings.aiModel = preset.model;
          await this.plugin.savePluginData();
          if (urlInputRef)
            urlInputRef.value = preset.url;
          if (modelInputRef)
            modelInputRef.value = preset.model;
          if (keyHintEl)
            keyHintEl.textContent = `Key-Format: ${preset.keyHint}`;
          new import_obsidian4.Notice(`\u2713 ${label} geladen`, 2e3);
        })
      );
    }
    new import_obsidian4.Setting(containerEl).setName("Base URL").setDesc("OpenAI-kompatibler API-Endpunkt.").addText((text) => {
      urlInputRef = text.inputEl;
      text.setValue(this.plugin.pluginData.settings.aiBaseUrl).onChange(async (value) => {
        this.plugin.pluginData.settings.aiBaseUrl = value;
        await this.plugin.savePluginData();
      });
    });
    const keySetting = new import_obsidian4.Setting(containerEl).setName("API Key").setDesc("F\xFCr Ollama: 'ollama'. F\xFCr Cloud-Provider: dein pers\xF6nlicher Key.");
    keyHintEl = keySetting.descEl.createEl("span", { cls: "remnote-key-hint" });
    keySetting.addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("API Key eingeben\u2026").setValue(this.plugin.pluginData.settings.aiApiKey).onChange(async (value) => {
        this.plugin.pluginData.settings.aiApiKey = value;
        await this.plugin.savePluginData();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Modell").setDesc("Modellname exakt wie vom Provider erwartet.").addText((text) => {
      modelInputRef = text.inputEl;
      text.setValue(this.plugin.pluginData.settings.aiModel).onChange(async (value) => {
        this.plugin.pluginData.settings.aiModel = value;
        await this.plugin.savePluginData();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Verbindung testen").setDesc("Sendet eine kurze Testfrage \u2014 best\xE4tigt dass Key, URL und Modell korrekt sind.").addButton(
      (btn) => btn.setButtonText("Test").setCta().onClick(async () => {
        const tmpSettings = { ...this.plugin.pluginData.settings, aiEnabled: true };
        try {
          const result = await aiGenerateAnswer(
            "What is photosynthesis? Answer in one sentence.",
            "",
            tmpSettings
          );
          new import_obsidian4.Notice("\u2713 AI OK: " + result.slice(0, 120), 6e3);
        } catch (e) {
          new import_obsidian4.Notice("\u2717 AI Fehler: " + e.message, 8e3);
        }
      })
    );
  }
  renderGroupList(container) {
    container.empty();
    const groups = this.plugin.pluginData.settings.examGroups;
    if (groups.length === 0) {
      container.createEl("p", {
        text: "Noch keine Pr\xFCfungen angelegt.",
        cls: "remnote-settings-empty"
      });
      return;
    }
    for (const group of groups) {
      const row = container.createDiv("remnote-settings-group-row");
      const info = row.createDiv("remnote-settings-group-info");
      info.createEl("span", { text: group.name, cls: "remnote-settings-group-name" });
      info.createEl("span", {
        text: group.examDate ? `  \u{1F4C5} ${group.examDate}` : "  (kein Datum)",
        cls: "remnote-settings-group-date"
      });
      info.createEl("span", {
        text: `  ${group.paths.length} Pfad(e)`,
        cls: "remnote-settings-group-paths"
      });
      const actions = row.createDiv("remnote-settings-group-actions");
      const editBtn = actions.createEl("button", { text: "Bearbeiten", cls: "remnote-btn-small" });
      editBtn.onclick = () => {
        new ExamGroupModal(this.app, group, async (saved) => {
          const idx = this.plugin.pluginData.settings.examGroups.findIndex((g) => g.id === saved.id);
          if (idx !== -1) {
            this.plugin.pluginData.settings.examGroups[idx] = saved;
          }
          await this.plugin.savePluginData();
          this.display();
        }).open();
      };
      const delBtn = actions.createEl("button", { text: "\xD7", cls: "remnote-btn-small remnote-btn-delete" });
      delBtn.onclick = async () => {
        this.plugin.pluginData.settings.examGroups = this.plugin.pluginData.settings.examGroups.filter((g) => g.id !== group.id);
        await this.plugin.savePluginData();
        this.display();
      };
    }
  }
};

// src/pdf-panel.ts
var import_obsidian5 = require("obsidian");
var PDF_PANEL_VIEW_TYPE = "remnote-pdf-panel";
var PdfFileSuggest = class extends import_obsidian5.FuzzySuggestModal {
  constructor(app, onChoose) {
    super(app);
    this.onChoose = onChoose;
    this.setPlaceholder("PDF aus Vault ausw\xE4hlen\u2026");
  }
  getItems() {
    return this.app.vault.getFiles().filter((f) => f.extension === "pdf");
  }
  getItemText(f) {
    return f.path;
  }
  onChooseItem(f) {
    this.onChoose(f);
  }
};
var PdfPanelView = class extends import_obsidian5.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.notePath = null;
    this.pdfPaths = [];
    this.activeIdx = 0;
    this.currentPage = 1;
    // DOM refs
    this.tabBar = null;
    this.pageInput = null;
    this.statusEl = null;
    this.pdfContainer = null;
    // Obsidian embed lives here
    this.dropOverlay = null;
    this.plugin = plugin;
  }
  getViewType() {
    return PDF_PANEL_VIEW_TYPE;
  }
  getDisplayText() {
    return "PDF Panel";
  }
  getIcon() {
    return "file-text";
  }
  async onOpen() {
    this.buildShell();
    this.registerEvent(this.app.workspace.on("active-leaf-change", () => this.syncToActiveNote()));
    this.registerEvent(this.app.workspace.on("file-open", () => this.syncToActiveNote()));
    this.syncToActiveNote();
  }
  async onClose() {
    this.contentEl.empty();
  }
  // ── Sync to whichever note is open ───────────────────────────────────────
  syncToActiveNote() {
    var _a;
    const active = this.app.workspace.getActiveFile();
    if (!active || active.extension !== "md")
      return;
    if (active.path === this.notePath)
      return;
    this.notePath = active.path;
    this.pdfPaths = [...(_a = this.plugin.pluginData.pdfLinks[this.notePath]) != null ? _a : []];
    this.activeIdx = 0;
    this.currentPage = 1;
    this.refreshTabs();
    this.renderPdf();
  }
  // ── Build the static DOM shell ────────────────────────────────────────────
  buildShell() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("remnote-pdf-panel");
    const toolbar = contentEl.createDiv("remnote-pdf-toolbar");
    this.tabBar = toolbar.createDiv("remnote-pdf-tabs");
    const btnRow = toolbar.createDiv("remnote-pdf-btn-row");
    const addBtn = btnRow.createEl("button", { cls: "remnote-pdf-btn", title: "PDF aus Vault hinzuf\xFCgen" });
    addBtn.innerHTML = `<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg> PDF`;
    addBtn.onclick = () => this.addPdfFromVault();
    const delBtn = btnRow.createEl("button", { cls: "remnote-pdf-btn remnote-pdf-btn-danger", title: "Dieses PDF entfernen" });
    delBtn.innerHTML = `<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6l-1 14H6L5 6"/><path d="M10 11v6M14 11v6"/></svg>`;
    delBtn.onclick = () => this.removeActivePdf();
    const navBar = contentEl.createDiv("remnote-pdf-nav");
    const prevBtn = navBar.createEl("button", { cls: "remnote-pdf-nav-btn", title: "Vorherige Seite (Alt+\u2190)" });
    prevBtn.innerHTML = `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="15 18 9 12 15 6"/></svg>`;
    prevBtn.onclick = () => this.gotoPage(this.currentPage - 1);
    navBar.createEl("span", { text: "Seite", cls: "remnote-pdf-page-label" });
    this.pageInput = navBar.createEl("input", { type: "number", cls: "remnote-pdf-page-input", value: "1" });
    this.pageInput.min = "1";
    this.pageInput.onchange = () => {
      const v = parseInt(this.pageInput.value);
      if (!isNaN(v) && v > 0)
        this.gotoPage(v);
    };
    this.pageInput.onkeydown = (e) => {
      if (e.key === "Enter")
        e.target.blur();
    };
    const nextBtn = navBar.createEl("button", { cls: "remnote-pdf-nav-btn", title: "N\xE4chste Seite (Alt+\u2192)" });
    nextBtn.innerHTML = `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="9 18 15 12 9 6"/></svg>`;
    nextBtn.onclick = () => this.gotoPage(this.currentPage + 1);
    navBar.createDiv("remnote-pdf-nav-spacer");
    const linkBtn = navBar.createEl("button", { cls: "remnote-pdf-btn remnote-pdf-btn-link", title: "[[pdf#page=N]] in Notiz einf\xFCgen" });
    linkBtn.innerHTML = `<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/></svg> Seite verkn\xFCpfen`;
    linkBtn.onclick = () => this.insertPageRef();
    this.registerDomEvent(document, "keydown", (e) => {
      if (!this.isVisible())
        return;
      if (e.target.closest("input,textarea"))
        return;
      if (e.altKey && e.key === "ArrowLeft") {
        e.preventDefault();
        this.gotoPage(this.currentPage - 1);
      }
      if (e.altKey && e.key === "ArrowRight") {
        e.preventDefault();
        this.gotoPage(this.currentPage + 1);
      }
    });
    const mainArea = contentEl.createDiv("remnote-pdf-main");
    this.statusEl = mainArea.createDiv("remnote-pdf-status");
    this.pdfContainer = mainArea.createDiv("remnote-pdf-container");
    this.dropOverlay = mainArea.createDiv("remnote-pdf-drop-overlay");
    this.dropOverlay.innerHTML = `
      <div class="remnote-pdf-drop-icon">\u{1F4E5}</div>
      <div class="remnote-pdf-drop-title">PDF hier ablegen</div>
      <div class="remnote-pdf-drop-sub">Wird in Vault importiert und verkn\xFCpft</div>
    `;
    this.attachDragDrop(mainArea);
    this.refreshTabs();
    this.renderPdf();
  }
  // ── Render PDF using Obsidian's native embed ──────────────────────────────
  async renderPdf() {
    var _a;
    if (!this.pdfContainer || !this.statusEl)
      return;
    this.pdfContainer.empty();
    if (this.pdfPaths.length === 0) {
      this.pdfContainer.style.display = "none";
      this.statusEl.style.display = "flex";
      this.statusEl.innerHTML = this.notePath ? `<div class="remnote-pdf-status-icon">\u{1F4C4}</div>
           <div class="remnote-pdf-status-text">Kein PDF verkn\xFCpft</div>
           <div class="remnote-pdf-status-sub">PDF aus Windows Explorer hier reinziehen<br>oder "+ PDF" f\xFCr ein PDF aus dem Vault</div>` : `<div class="remnote-pdf-status-icon">\u{1F4DD}</div>
           <div class="remnote-pdf-status-text">Keine Notiz ge\xF6ffnet</div>
           <div class="remnote-pdf-status-sub">\xD6ffne eine Notiz um ihre PDFs anzuzeigen</div>`;
      return;
    }
    this.pdfContainer.style.display = "block";
    this.statusEl.style.display = "none";
    const pdfPath = this.pdfPaths[this.activeIdx];
    const pdfFile = this.app.vault.getAbstractFileByPath(pdfPath);
    if (!(pdfFile instanceof import_obsidian5.TFile)) {
      new import_obsidian5.Notice(`PDF nicht im Vault gefunden: ${pdfPath}`);
      return;
    }
    if (this.pageInput)
      this.pageInput.value = String(this.currentPage);
    const embedSyntax = `![[${pdfPath}#page=${this.currentPage}]]`;
    await import_obsidian5.MarkdownRenderer.render(
      this.app,
      embedSyntax,
      this.pdfContainer,
      (_a = this.notePath) != null ? _a : pdfPath,
      this.plugin
    );
    this.expandEmbedHeight();
  }
  /** Make the embedded PDF viewer fill the available panel height */
  expandEmbedHeight() {
    if (!this.pdfContainer)
      return;
    const applyHeight = () => {
      const embed = this.pdfContainer.querySelector(".pdf-embed");
      if (embed) {
        embed.style.height = "100%";
        embed.style.maxHeight = "none";
      }
      const inner = this.pdfContainer.querySelector(
        ".pdf-embed iframe, .pdf-embed object, .pdf-embed embed"
      );
      if (inner) {
        inner.style.height = "100%";
        inner.style.minHeight = "400px";
      }
    };
    applyHeight();
    setTimeout(applyHeight, 150);
    setTimeout(applyHeight, 500);
  }
  // ── Navigation ────────────────────────────────────────────────────────────
  gotoPage(page) {
    if (page < 1)
      return;
    this.currentPage = page;
    if (this.pageInput)
      this.pageInput.value = String(page);
    const navigated = this.tryNavigateInPlace(page);
    if (!navigated)
      this.renderPdf();
  }
  /**
   * Attempt to jump to a page inside the already-rendered Obsidian PDF embed
   * without destroying and re-creating the whole embed (avoids flicker).
   * Returns true if navigation succeeded.
   */
  tryNavigateInPlace(page) {
    if (!this.pdfContainer)
      return false;
    const iframe = this.pdfContainer.querySelector(
      ".pdf-embed iframe"
    );
    if (!iframe)
      return false;
    try {
      const src = iframe.src || "";
      if (!src)
        return false;
      const base = src.split("#")[0];
      iframe.src = `${base}#page=${page}`;
      return true;
    } catch (e) {
      return false;
    }
  }
  // ── Insert [[pdf#page=N]] into active note ────────────────────────────────
  insertPageRef() {
    var _a;
    if (this.pdfPaths.length === 0) {
      new import_obsidian5.Notice("Kein PDF aktiv.");
      return;
    }
    const pdfName = (_a = this.pdfPaths[this.activeIdx].split("/").pop()) != null ? _a : "";
    const ref = `[[${pdfName}#page=${this.currentPage}]]`;
    const view = this.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
    if (view == null ? void 0 : view.editor) {
      view.editor.replaceRange(ref, view.editor.getCursor());
      new import_obsidian5.Notice(`\u2713 Referenz eingef\xFCgt: ${ref}`, 2e3);
    } else {
      navigator.clipboard.writeText(ref).then(() => new import_obsidian5.Notice(`Referenz kopiert: ${ref}`, 3e3));
    }
  }
  // ── Public: jump to a specific PDF + page (called from link click handler) ─
  async openPdfAtPage(pdfPath, page) {
    if (!this.pdfPaths.includes(pdfPath)) {
      await this.linkPdf(pdfPath);
    }
    const idx = this.pdfPaths.indexOf(pdfPath);
    if (idx !== -1 && idx !== this.activeIdx) {
      this.activeIdx = idx;
      this.refreshTabs();
    }
    this.currentPage = page;
    if (this.pageInput)
      this.pageInput.value = String(page);
    const navigated = this.tryNavigateInPlace(page);
    if (!navigated)
      await this.renderPdf();
  }
  // ── Drag & Drop ───────────────────────────────────────────────────────────
  attachDragDrop(target) {
    let depth = 0;
    target.addEventListener("dragenter", (e) => {
      if (!this.hasPdfFiles(e.dataTransfer))
        return;
      e.preventDefault();
      depth++;
      if (depth === 1)
        this.showOverlay(true);
    });
    target.addEventListener("dragleave", () => {
      depth--;
      if (depth <= 0) {
        depth = 0;
        this.showOverlay(false);
      }
    });
    target.addEventListener("dragover", (e) => {
      if (!this.hasPdfFiles(e.dataTransfer))
        return;
      e.preventDefault();
      e.dataTransfer.dropEffect = "copy";
    });
    target.addEventListener("drop", async (e) => {
      var _a;
      e.preventDefault();
      depth = 0;
      this.showOverlay(false);
      const files = (_a = e.dataTransfer) == null ? void 0 : _a.files;
      if (!files)
        return;
      for (let i = 0; i < files.length; i++) {
        const f = files[i];
        if (f.name.toLowerCase().endsWith(".pdf") || f.type === "application/pdf")
          await this.importDroppedPdf(f);
      }
    });
  }
  hasPdfFiles(dt) {
    return !!dt && Array.from(dt.types).includes("Files");
  }
  showOverlay(show) {
    if (this.dropOverlay)
      this.dropOverlay.style.display = show ? "flex" : "none";
  }
  // ── Import PDF dropped from OS ────────────────────────────────────────────
  async importDroppedPdf(file) {
    var _a, _b, _c;
    if (!this.notePath) {
      new import_obsidian5.Notice("Keine Notiz ge\xF6ffnet.");
      return;
    }
    const fileName = file.name;
    const folder = (this.plugin.pluginData.settings.pdfAttachmentFolder || "Attachments/PDFs").replace(/\/$/, "");
    const destPath = `${folder}/${fileName}`;
    const vaultBase = ((_a = this.app.vault.adapter.basePath) != null ? _a : "").replace(/\\/g, "/");
    const electronPath = ((_b = file.path) != null ? _b : "").replace(/\\/g, "/");
    if (vaultBase && electronPath.startsWith(vaultBase)) {
      const rel = electronPath.slice(vaultBase.length).replace(/^\//, "");
      await this.linkPdf(rel);
      new import_obsidian5.Notice(`"${fileName}" ist bereits im Vault \u2014 verkn\xFCpft`, 2e3);
      return;
    }
    if (await this.app.vault.adapter.exists(destPath)) {
      await this.linkPdf(destPath);
      new import_obsidian5.Notice(`"${fileName}" existiert bereits im Vault \u2014 verkn\xFCpft`, 2e3);
      return;
    }
    if (!await this.app.vault.adapter.exists(folder))
      await this.app.vault.createFolder(folder);
    const notice = new import_obsidian5.Notice(`Importiere "${fileName}"\u2026`, 0);
    try {
      await this.app.vault.adapter.writeBinary(destPath, await file.arrayBuffer());
      notice.hide();
      await this.linkPdf(destPath);
      new import_obsidian5.Notice(`\u2713 "${fileName}" \u2192 ${destPath}`, 4e3);
    } catch (err) {
      notice.hide();
      new import_obsidian5.Notice(`Import fehlgeschlagen: ${(_c = err.message) != null ? _c : err}`, 5e3);
    }
  }
  // ── Link a vault PDF to the current note ─────────────────────────────────
  async linkPdf(vaultPath) {
    if (!this.notePath)
      return;
    if (this.pdfPaths.includes(vaultPath)) {
      const idx = this.pdfPaths.indexOf(vaultPath);
      this.activeIdx = idx;
      this.currentPage = 1;
      this.refreshTabs();
      this.renderPdf();
      return;
    }
    this.pdfPaths.push(vaultPath);
    this.plugin.pluginData.pdfLinks[this.notePath] = [...this.pdfPaths];
    await this.plugin.savePluginData();
    this.activeIdx = this.pdfPaths.length - 1;
    this.currentPage = 1;
    this.refreshTabs();
    this.renderPdf();
  }
  // ── Tab bar ───────────────────────────────────────────────────────────────
  refreshTabs() {
    var _a, _b;
    if (!this.tabBar)
      return;
    this.tabBar.empty();
    if (this.pdfPaths.length === 0) {
      this.tabBar.createEl("span", {
        text: this.notePath ? "Kein PDF \u2014 PDF reinziehen oder + klicken" : "Keine Notiz ge\xF6ffnet",
        cls: "remnote-pdf-no-pdf"
      });
      return;
    }
    for (let i = 0; i < this.pdfPaths.length; i++) {
      const name = (_b = (_a = this.pdfPaths[i].split("/").pop()) == null ? void 0 : _a.replace(/\.pdf$/i, "")) != null ? _b : "";
      const tab = this.tabBar.createEl("button", {
        cls: "remnote-pdf-tab" + (i === this.activeIdx ? " active" : ""),
        title: this.pdfPaths[i]
      });
      tab.setText(name);
      tab.onclick = () => {
        this.activeIdx = i;
        this.currentPage = 1;
        this.refreshTabs();
        this.renderPdf();
      };
    }
  }
  // ── Manage linked PDFs ────────────────────────────────────────────────────
  addPdfFromVault() {
    if (!this.notePath) {
      new import_obsidian5.Notice("Keine Notiz ge\xF6ffnet.");
      return;
    }
    new PdfFileSuggest(this.app, (f) => this.linkPdf(f.path)).open();
  }
  async removeActivePdf() {
    if (this.pdfPaths.length === 0)
      return;
    const removed = this.pdfPaths[this.activeIdx].split("/").pop();
    this.pdfPaths.splice(this.activeIdx, 1);
    if (this.notePath) {
      if (this.pdfPaths.length === 0)
        delete this.plugin.pluginData.pdfLinks[this.notePath];
      else
        this.plugin.pluginData.pdfLinks[this.notePath] = [...this.pdfPaths];
      await this.plugin.savePluginData();
    }
    this.activeIdx = Math.max(0, this.activeIdx - 1);
    this.currentPage = 1;
    this.refreshTabs();
    this.renderPdf();
    new import_obsidian5.Notice(`"${removed}" entfernt`, 2e3);
  }
  isVisible() {
    return this.leaf.view === this;
  }
};

// src/main.ts
var RemNoteFlashcardsPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.pluginData = {
      settings: { ...DEFAULT_SETTINGS },
      reviews: {},
      lastReminderDate: "",
      pdfLinks: {}
    };
    this.allCards = [];
    this.ribbonBadgeEl = null;
  }
  async onload() {
    await this.loadPluginData();
    this.registerView(PDF_PANEL_VIEW_TYPE, (leaf) => new PdfPanelView(leaf, this));
    const ribbonIcon = this.addRibbonIcon("layers", "RemNote Flashcards", async () => {
      await this.openSessionPicker();
    });
    this.ribbonBadgeEl = ribbonIcon.createSpan("remnote-ribbon-badge");
    this.addRibbonIcon("file-text", "PDF Panel \xF6ffnen", () => this.openPdfPanel());
    this.addCommand({
      id: "open-session-picker",
      name: "Lernsitzung starten",
      callback: () => this.openSessionPicker()
    });
    this.addCommand({
      id: "review-current-note",
      name: "Aktive Notiz lernen",
      callback: () => this.reviewCurrentNote()
    });
    this.addCommand({
      id: "show-stats",
      name: "Statistiken anzeigen",
      callback: () => this.showStats()
    });
    this.addCommand({
      id: "browse-cards",
      name: "Karteikarten durchsuchen",
      callback: () => this.browseCards()
    });
    this.addCommand({
      id: "open-pdf-panel",
      name: "PDF Panel \xF6ffnen",
      callback: () => this.openPdfPanel()
    });
    this.addCommand({
      id: "pdf-insert-page-ref",
      name: "PDF: Seitenreferenz in Notiz einf\xFCgen",
      callback: () => this.pdfInsertRef()
    });
    this.addCommand({
      id: "ai-autofill-card",
      name: "AI: Antwort f\xFCr Karte auf dieser Zeile generieren",
      editorCallback: async (editor) => {
        await this.aiAutofillCard(editor);
      }
    });
    this.addSettingTab(new RemNoteSettingsTab(this.app, this));
    this.registerMarkdownPostProcessor((el) => {
      el.querySelectorAll("a.internal-link").forEach((linkEl) => {
        var _a, _b;
        const href = (_b = (_a = linkEl.getAttribute("data-href")) != null ? _a : linkEl.getAttribute("href")) != null ? _b : "";
        if (!href.match(/\.pdf(#|$)/i))
          return;
        const hashIdx = href.lastIndexOf("#");
        const pdfRef = hashIdx !== -1 ? href.slice(0, hashIdx) : href;
        const fragment = hashIdx !== -1 ? href.slice(hashIdx + 1) : "";
        const pageNum = parseInt(fragment.replace(/^page=/i, "")) || 1;
        linkEl.addEventListener("click", async (e) => {
          e.preventDefault();
          e.stopPropagation();
          const pdfFile = this.app.vault.getFiles().find(
            (f) => f.name === pdfRef || f.path === pdfRef || f.basename === pdfRef
          );
          if (!pdfFile) {
            new import_obsidian6.Notice(`PDF nicht gefunden: ${pdfRef}`);
            return;
          }
          await this.openPdfPanel();
          await new Promise((r) => setTimeout(r, 80));
          const leaves = this.app.workspace.getLeavesOfType(PDF_PANEL_VIEW_TYPE);
          if (leaves.length === 0)
            return;
          const view = leaves[0].view;
          await view.openPdfAtPage(pdfFile.path, pageNum);
        });
      });
    });
    this.app.workspace.onLayoutReady(async () => {
      await this.scanVault();
      this.updateBadge();
      this.checkDailyReminder();
    });
    this.registerEvent(
      this.app.vault.on("modify", async (file) => {
        if (file instanceof import_obsidian6.TFile && file.extension === "md") {
          await this.scanFile(file);
          this.updateBadge();
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("create", async (file) => {
        if (file instanceof import_obsidian6.TFile && file.extension === "md") {
          await this.scanFile(file);
          this.updateBadge();
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file instanceof import_obsidian6.TFile) {
          this.allCards = this.allCards.filter((c) => c.filePath !== file.path);
          this.updateBadge();
        }
      })
    );
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(PDF_PANEL_VIEW_TYPE);
  }
  // ── Data persistence ───────────────────────────────────────
  async loadPluginData() {
    var _a, _b, _c;
    const raw = await this.loadData();
    if (raw) {
      this.pluginData = {
        settings: { ...DEFAULT_SETTINGS, ...raw.settings },
        reviews: (_a = raw.reviews) != null ? _a : {},
        lastReminderDate: (_b = raw.lastReminderDate) != null ? _b : "",
        pdfLinks: (_c = raw.pdfLinks) != null ? _c : {}
      };
      const s = this.pluginData.settings;
      if (s.examDate && this.pluginData.settings.examGroups.length === 0) {
        this.pluginData.settings.examGroups = [{
          id: "migrated",
          name: "Pr\xFCfung",
          examDate: s.examDate,
          paths: []
        }];
        delete s.examDate;
        await this.savePluginData();
      }
    }
  }
  async savePluginData() {
    await this.saveData(this.pluginData);
  }
  // ── Vault scanning ─────────────────────────────────────────
  async scanVault() {
    this.allCards = [];
    const files = this.app.vault.getMarkdownFiles();
    for (const file of files) {
      await this.scanFile(file, false);
    }
  }
  async scanFile(file, merge = true) {
    const content = await this.app.vault.read(file);
    const cards = parseFlashcards(content, file.path);
    if (merge) {
      this.allCards = this.allCards.filter((c) => c.filePath !== file.path);
      this.allCards.push(...cards);
    } else {
      this.allCards.push(...cards);
    }
  }
  // ── Badge ──────────────────────────────────────────────────
  updateBadge() {
    if (!this.ribbonBadgeEl)
      return;
    const due = getTotalDueCount(this.allCards, this.pluginData);
    if (due > 0) {
      this.ribbonBadgeEl.setText(due > 99 ? "99+" : String(due));
      this.ribbonBadgeEl.style.display = "flex";
    } else {
      this.ribbonBadgeEl.style.display = "none";
    }
  }
  // ── Daily reminder ─────────────────────────────────────────
  checkDailyReminder() {
    if (!this.pluginData.settings.dailyReminderEnabled)
      return;
    const today = todayStr();
    if (this.pluginData.lastReminderDate === today)
      return;
    const due = getTotalDueCount(this.allCards, this.pluginData);
    if (due > 0) {
      const groups = this.pluginData.settings.examGroups;
      let urgentMsg = "";
      if (groups.length > 0) {
        const sorted = groups.filter((g) => g.examDate).sort((a, b) => a.examDate.localeCompare(b.examDate));
        if (sorted.length > 0) {
          const next = sorted[0];
          const days = Math.max(0, Math.round(
            (new Date(next.examDate).getTime() - Date.now()) / 864e5
          ));
          urgentMsg = ` \u2014 ${next.name} in ${days} Tagen`;
        }
      }
      new import_obsidian6.Notice(
        `\u{1F4DA} RemNote Flashcards: ${due} Karten heute f\xE4llig${urgentMsg}.
Klicke auf das Karten-Icon in der Sidebar.`,
        8e3
      );
    }
    this.pluginData.lastReminderDate = today;
    this.savePluginData();
  }
  // ── Session actions ────────────────────────────────────────
  async openSessionPicker() {
    await this.scanVault();
    new SessionPickerModal(this.app, this, this.allCards).open();
  }
  async reviewCurrentNote() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian6.Notice("Keine aktive Notiz ge\xF6ffnet.");
      return;
    }
    await this.scanFile(activeFile);
    const cards = this.allCards.filter((c) => c.filePath === activeFile.path);
    if (cards.length === 0) {
      new import_obsidian6.Notice("Keine Karteikarten in dieser Notiz.\nVerwende :: oder ::: zum Erstellen.");
      return;
    }
    new ReviewModal(this.app, this, cards, this.pluginData).open();
  }
  async showStats() {
    await this.scanVault();
    const stats = getStats(this.allCards, this.pluginData);
    const groups = this.pluginData.settings.examGroups;
    let groupLines = "";
    if (groups.length > 0) {
      for (const g of groups) {
        const { due, total } = getStats(
          this.allCards.filter((c) => cardBelongsToGroup(c, g)),
          this.pluginData
        );
        groupLines += `
  ${g.name}: ${due} f\xE4llig / ${total} gesamt`;
      }
    }
    new import_obsidian6.Notice(
      `\u{1F4CA} RemNote Flashcards

Gesamt: ${stats.total} Karten
\u2705 Gelernt: ${stats.learned}
\u{1F534} F\xE4llig: ${stats.due}
\u{1F195} Neu: ${stats.unseen}` + (groupLines ? `

Nach Pr\xFCfung:${groupLines}` : ""),
      12e3
    );
  }
  async browseCards() {
    await this.scanVault();
    new BrowseModal(this.app, this, this.allCards, this.pluginData).open();
  }
  // ── PDF Panel ──────────────────────────────────────────────
  async openPdfPanel() {
    const existing = this.app.workspace.getLeavesOfType(PDF_PANEL_VIEW_TYPE);
    if (existing.length > 0) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.app.workspace.getRightLeaf(false);
    if (!leaf)
      return;
    await leaf.setViewState({ type: PDF_PANEL_VIEW_TYPE, active: true });
    this.app.workspace.revealLeaf(leaf);
  }
  pdfInsertRef() {
    const leaves = this.app.workspace.getLeavesOfType(PDF_PANEL_VIEW_TYPE);
    if (leaves.length === 0) {
      new import_obsidian6.Notice("PDF Panel ist nicht ge\xF6ffnet. \xD6ffne es zuerst mit 'PDF Panel \xF6ffnen'.");
      return;
    }
    const view = leaves[0].view;
    view.insertPageRef();
  }
  // ── AI Autofill (while writing) ────────────────────────────
  async aiAutofillCard(editor) {
    if (!this.pluginData.settings.aiEnabled) {
      new import_obsidian6.Notice("AI ist nicht aktiviert. Bitte in Einstellungen \u2192 AI aktivieren.");
      return;
    }
    const cursor = editor.getCursor();
    const lineText = editor.getLine(cursor.line);
    let front = "";
    let insertPos = lineText.length;
    const tripleIdx = lineText.indexOf(":::");
    if (tripleIdx !== -1) {
      const after = lineText.slice(tripleIdx + 3).trim();
      if (after !== "") {
        new import_obsidian6.Notice("Diese Zeile hat bereits eine Antwort.");
        return;
      }
      front = lineText.slice(0, tripleIdx).trim();
      insertPos = lineText.length;
    } else {
      const basicIdx = lineText.indexOf("::");
      if (basicIdx !== -1) {
        const after = lineText.slice(basicIdx + 2).trim();
        if (after !== "") {
          new import_obsidian6.Notice("Diese Zeile hat bereits eine Antwort.");
          return;
        }
        front = lineText.slice(0, basicIdx).trim();
        insertPos = lineText.length;
      }
    }
    if (!front) {
      new import_obsidian6.Notice("Kein :: oder ::: auf dieser Zeile gefunden.\nBeispiel: Frage :: ");
      return;
    }
    const notice = new import_obsidian6.Notice("\u2726 AI generiert Antwort...", 0);
    try {
      const answer = await aiGenerateAnswer(front, "", this.pluginData.settings);
      notice.hide();
      if (!answer) {
        new import_obsidian6.Notice("AI hat keine Antwort zur\xFCckgegeben.");
        return;
      }
      editor.replaceRange(
        " " + answer,
        { line: cursor.line, ch: insertPos },
        { line: cursor.line, ch: insertPos }
      );
      new import_obsidian6.Notice("\u2713 Antwort eingef\xFCgt", 2e3);
    } catch (e) {
      notice.hide();
      new import_obsidian6.Notice("AI Fehler: " + e.message);
    }
  }
};
